package lt.vu.mybatis.dao;

import lt.vu.mybatis.model.Forest;
import org.mybatis.cdi.Mapper;
import java.util.List;

public interface ForestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FOREST
     *
     * @mbg.generated Mon May 24 15:21:56 EEST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FOREST
     *
     * @mbg.generated Mon May 24 15:21:56 EEST 2021
     */
    int insert(Forest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FOREST
     *
     * @mbg.generated Mon May 24 15:21:56 EEST 2021
     */
    Forest selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FOREST
     *
     * @mbg.generated Mon May 24 15:21:56 EEST 2021
     */
    List<Forest> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FOREST
     *
     * @mbg.generated Mon May 24 15:21:56 EEST 2021
     */
    int updateByPrimaryKey(Forest record);
}