package lt.vu.mybatis.dao;

import lt.vu.mybatis.model.Tree;
import org.mybatis.cdi.Mapper;
import java.util.List;
@Mapper
public interface TreeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TREE
     *
     * @mbg.generated Mon May 24 15:21:56 EEST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TREE
     *
     * @mbg.generated Mon May 24 15:21:56 EEST 2021
     */
    int insert(Tree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TREE
     *
     * @mbg.generated Mon May 24 15:21:56 EEST 2021
     */
    Tree selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TREE
     *
     * @mbg.generated Mon May 24 15:21:56 EEST 2021
     */
    List<Tree> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TREE
     *
     * @mbg.generated Mon May 24 15:21:56 EEST 2021
     */
    int updateByPrimaryKey(Tree record);
}