package lt.vu.mybatis.model;

public class Tree {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TREE.ID
     *
     * @mbg.generated Mon May 24 15:21:56 EEST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TREE.DESCRIPTION
     *
     * @mbg.generated Mon May 24 15:21:56 EEST 2021
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TREE.NAME
     *
     * @mbg.generated Mon May 24 15:21:56 EEST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TREE.VERSION
     *
     * @mbg.generated Mon May 24 15:21:56 EEST 2021
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TREE.ID
     *
     * @return the value of PUBLIC.TREE.ID
     *
     * @mbg.generated Mon May 24 15:21:56 EEST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TREE.ID
     *
     * @param id the value for PUBLIC.TREE.ID
     *
     * @mbg.generated Mon May 24 15:21:56 EEST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TREE.DESCRIPTION
     *
     * @return the value of PUBLIC.TREE.DESCRIPTION
     *
     * @mbg.generated Mon May 24 15:21:56 EEST 2021
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TREE.DESCRIPTION
     *
     * @param description the value for PUBLIC.TREE.DESCRIPTION
     *
     * @mbg.generated Mon May 24 15:21:56 EEST 2021
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TREE.NAME
     *
     * @return the value of PUBLIC.TREE.NAME
     *
     * @mbg.generated Mon May 24 15:21:56 EEST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TREE.NAME
     *
     * @param name the value for PUBLIC.TREE.NAME
     *
     * @mbg.generated Mon May 24 15:21:56 EEST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TREE.VERSION
     *
     * @return the value of PUBLIC.TREE.VERSION
     *
     * @mbg.generated Mon May 24 15:21:56 EEST 2021
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TREE.VERSION
     *
     * @param version the value for PUBLIC.TREE.VERSION
     *
     * @mbg.generated Mon May 24 15:21:56 EEST 2021
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}